site_name: CoDecomp
site_url: https://github.com/han190/co-decomp
repo_url: https://github.com/han190/co-decomp
site_author: Han Tang
copyright: Copyright &copy; 2024 Han Tang

theme:
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Follow system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/icon.svg
  logo: assets/icon.svg

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences